baseURL: "https://sergeykibish.com/"
languageCode: "en-us"
title: "Sergey Kibish - Experienced Multifunctional Software Engineer"

enableRobotsTXT: true
enableEmoji: true
googleAnalytics: "UA-103073257-1"
taxonomies: []
disableKinds: ["RSS", "sitemap"]

params:
  Author: "Sergey Kibish"
  Description: "Creator, developer, a person with not a standard thinking"
  Email: "sergey@kibish.com"
  About: >
    Skilled in different languages / tools / technologies.
    Strong engineering professional with a Master of Science (Mg.Sc.Comp.) focused in Computer Science.
    Natural-born leader, full of passion and charisma. A hobby is music in all of its manifestations (listening, playing, writing).
