baseURL: "https://sergeykibish.com"
languageCode: "en-us"
copyright: "&#169; Sergey Kibish"
author:
  name: "Sergey Kibish"
  email: "contact@sergeykibish.com"

enableRobotsTXT: true
enableEmoji: true
disqusShortname: sergey-kibish-blog
taxonomies:
  category: blog/categories
  tag: blog/tags
outputs:
  page: ["HTML"]
  home: ["HTML"]
  section: ["HTML","RSS"]

markup:
  highlight:
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: github
    tabWidth: 4

build:
  writeStats: true

menu:
  main:
  - name: Home
    url: /
    weight: -110
  - name: Blog
    pageRef: blog
    weight: -100
  - name: Music
    pageRef: music
    weight: -90
  - name: Speaking
    pageRef: speaking
    weight: -80
  - name: Others Say
    pageRef: others-say
    weight: -70

params:
  images:
    - /img/social-share.png
  description: "Problem solver. Sorting chaos."
  styles:
    # mainColor: "#0e131f"
    # secondColor: "#ab966d"
    # textColor: "#fbf5f3"

    # Mint
    mainColor: "#2171a4"
    secondColor: "#c7ba9d"
    textColor: "#f8f5f3"

    # Sea
    # mainColor: "#0fa3b1ff"
    # secondColor: "#b5e2faff"
    # textColor: "#f9f7f3ff"
