baseURL: "https://sergeykibish.com/"
languageCode: "en-us"
title: "Sergey Kibish - Experienced Multifunctional Software Engineer"

enableRobotsTXT: true
enableEmoji: true
googleAnalytics: "UA-103073257-1"
taxonomies: []
disableKinds: ["RSS", "sitemap"]

params:
  Author: "Sergey Kibish"
  Description: "Creator, developer, a person with not a standard thinking"
  Email: "sergey@kibish.com"
