baseURL: "https://sergeykibish.com/"
languageCode: "en-us"
copyright: "&#169; Sergey Kibish"
author:
  name: "Sergey Kibish"
  email: "sergey@kibish.com"

enableRobotsTXT: true
enableEmoji: true
googleAnalytics: "UA-103073257-1"
disqusShortname: sergey-kibish-blog
taxonomies: []
outputs:
    page: ["HTML"]
    home: ["HTML"]
    section: ["HTML","RSS"]

markup:
  highlight:
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: github
    tabWidth: 4

build:
  writeStats: true

menu:
  main:
  - name: Home
    pre: far fa-id-card
    url: /
    weight: -110
  - name: Blog
    pre: far fa-newspaper
    url: /blog/
    weight: -100

params:
  images:
    - /img/social-share.png
  description: "Creator, developer, a person with not a standard thinking"
  styles:
    # mainColor: "#0e131f"
    # secondColor: "#ab966d"
    # textColor: "#fbf5f3"

    # Mint
    mainColor: "#0091adff"
    secondColor: "#cdc392"
    textColor: "#fff4e4ff"

    # Sea
    # mainColor: "#0fa3b1ff"
    # secondColor: "#b5e2faff"
    # textColor: "#f9f7f3ff"
