baseURL: "https://sergeykibish.com/"
languageCode: "en-us"

enableRobotsTXT: true
enableEmoji: true
googleAnalytics: "UA-103073257-1"
disqusShortname: sergey-kibish-blog
taxonomies: []
disableKinds: ["RSS"]

markup:
  highlight:
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: solarized-light
    tabWidth: 4

build:
  writeStats: true

params:
  author: "Sergey Kibish"
  images:
    - /img/social-share.png
  description: "Creator, developer, a person with not a standard thinking"
  email: "sergey@kibish.com"
