name: Deploy

on:
  schedule:
    - cron: '0 7 * * *'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: "0.99.1"
        extended: true

    - uses: actions/setup-node@v3
      with:
        node-version: "16"
        cache: "npm"

    - name: Build
      run: |
        npm i
        hugo --minify

    - name: Publish
      run: ./node_modules/.bin/firebase deploy --message $GITHUB_SHA --project ${{ secrets.FIREBASE_PROJECT }} --token ${{ secrets.FIREBASE_TOKEN }}
