name: Deploy

on:
  schedule:
    - cron: '0 7 * * *'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: "0.111.3"
        extended: true

    - uses: actions/setup-node@v3
      with:
        node-version: "18"
        cache: "npm"

    - name: Build
      run: |
        npm i
        hugo --minify

    - name: Publish
      run: |
        set -e
        find public -type f | while read -r file
        do
          raw_file=${file##public/}
          curl --request PUT \
              --url https://storage.bunnycdn.com/${{ secrets.BUNNY_STORAGE }}/$raw_file
              --header 'AccessKey: ${{ secrets.BUNNY_API_STORAGE }}' \
              --header 'Content-Type: application/octet-stream' \
              --header 'accept: application/json'  \
              --data-binary @$file
        done

    - name: Refresh
      run: |
        set -e
        curl --request POST \
            --url https://api.bunny.net/pullzone/${{ secrets.BUNNY_PULL_ZONE }}/purgeCache \
            --header 'AccessKey: ${{ secrets.BUNNY_API }}' \
            --header 'content-type: application/json'
