name: Deploy

on:
  schedule:
    - cron: '0 7 * * *'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: "0.110.0"
        extended: true

    - uses: actions/setup-node@v3
      with:
        node-version: "18"
        cache: "npm"

    - name: Build
      run: |
        npm i
        hugo --minify

    - name: Publish
      run: |
        echo ${{ secrets.FIREBASE_SERVICE_ACCOUNT }} | base64 -d > sa.json
        GOOGLE_APPLICATION_CREDENTIALS=$GITHUB_WORKSPACE/sa.json ./node_modules/.bin/firebase deploy --message $GITHUB_SHA --project ${{ secrets.FIREBASE_PROJECT }}
        rm sa.json
