name: Deploy

on:
  schedule:
    - cron: '0 7 * * *'
  workflow_dispatch:

env:
  BUNNYSYNC_SHA256: "bc3188e0e55c1a9915713f4e7741e3daf56b7064962089884c7c7636d4383044"
  BUNNYSYNC_VERSION: "0.0.3"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: "0.119.0"
        extended: true

    - uses: actions/setup-node@v3
      with:
        node-version: "20"
        cache: "npm"

    - uses: actions/cache@v3
      with:
        path: resources
        key: ${{ runner.os }}-hugo-${{ github.run_id }}
        restore-keys: |
          ${{ runner.os }}-hugo

    - name: Build
      run: |
        npm install-clean
        hugo --gc --minify

    - name: Publish
      shell: bash
      run: |
        curl --silent \
            --location \
            --show-error \
            --output bunnysync \
            --url https://github.com/skibish/bunnysync/releases/download/${{ env.BUNNYSYNC_VERSION }}/bunnysync_${{ env.BUNNYSYNC_VERSION }}_linux_amd64

        echo "${{ env.BUNNYSYNC_SHA256 }} bunnysync" | sha256sum -c

        chmod +x bunnysync
        ./bunnysync -src ./public -zone-name ${{ secrets.BUNNY_STORAGE }} -password ${{ secrets.BUNNY_API_STORAGE }} | tee bunnysync.log

    - name: Refresh
      shell: bash
      run: |
        line_count=$(wc -l < bunnysync.log)

        if [ "$line_count" -eq 0 ]; then
          echo "Nothing to refresh"
          exit 0
        fi

        curl --silent \
            --show-error \
            --output /dev/null \
            --request POST \
            --url https://api.bunny.net/pullzone/${{ secrets.BUNNY_PULL_ZONE }}/purgeCache \
            --header 'AccessKey: ${{ secrets.BUNNY_API }}' \
            --header 'content-type: application/json'
