name: Deploy

on:
  schedule:
    - cron: '0 7 * * *'
  workflow_dispatch:

env:
  BUNNYSYNC_SHA265: "691e36fc2e2a94f68c86d55913f46f11e61709e3e2f8132f329d73b7d338043a"
  BUNNYSYNC_VERSION: "0.0.1"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: "0.119.0"
        extended: true

    - uses: actions/setup-node@v3
      with:
        node-version: "20"
        cache: "npm"

    - uses: actions/cache@v3
      with:
        path: resources
        key: ${{ runner.os }}-hugo-${{ github.run_id }}
        restore-keys: |
          ${{ runner.os }}-hugo

    - name: Build
      run: |
        npm install-clean
        hugo --minify

    - name: Publish
      run: |
        set -e

        curl --silent \
            --show-error \
            --output bunnysync \
            --url https://github.com/skibish/bunnysync/releases/download/${{ env.BUNNYSYNC_VERSION }}/bunnysync_${{ env.BUNNYSYNC_VERSION }}_linux_386

        echo "${{ env.BUNNYSYNC_SHA265 }} bunnysync" | sha256sum -c

        chmod +x bunnysync
        ./bunnysync -src ./public -storage-zone ${{ secrets.BUNNY_STORAGE }} -storage-api-key ${{ secrets.BUNNY_API_STORAGE }}

    - name: Refresh
      run: |
        set -e
        curl --silent \
            --show-error \
            --output /dev/null \
            --request POST \
            --url https://api.bunny.net/pullzone/${{ secrets.BUNNY_PULL_ZONE }}/purgeCache \
            --header 'AccessKey: ${{ secrets.BUNNY_API }}' \
            --header 'content-type: application/json'
