name: Deploy

on:
  push:
    branches: [ main ]
    paths-ignore:
    - 'README.md'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: "0.92.2"
        extended: true

    - uses: actions/setup-node@v1
      with:
        node-version: "16.x"

    - name: Build
      run: |
        npm i
        hugo --minify

    - name: Publish
      run: ./node_modules/.bin/firebase deploy --message $GITHUB_SHA --project ${{ secrets.FIREBASE_PROJECT }} --token ${{ secrets.FIREBASE_TOKEN }}
