name: Deploy

on:
  push:
    branches: [ master ]
    paths:
    - 'assets/**'
    - 'content/**'
    - 'data/**'
    - 'layouts/**'
    - 'static/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: peaceiris/actions-hugo@v2
      with:
        extended: true
    - uses: actions/setup-node@v1.4.2
      with:
        node-version: "14.x"

    - name: Build
      run: |
        npm i
        hugo --minify

    - name: Publish
      run: ./node_modules/.bin/firebase deploy --message $GITHUB_SHA --project ${{ secrets.FIREBASE_PROJECT }} --token ${{ secrets.FIREBASE_TOKEN }}
