name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: peaceiris/actions-hugo@v2
    - uses: actions/setup-node@v1.4.2
      with:
        node-version: "13.x"

    - name: Build
      run: |
        npm i
        hugo
        npm run build
        hugo --minify

    - name: Publish
      run: ./node_modules/.bin/firebase deploy --message ${{ GITHUB_SHA }} --project ${{ secrets.FIREBASE_PROJECT }} --token ${{ secrets.FIREBASE_TOKEN }}
