name: Deploy

on:
  schedule:
    - cron: '0 7 * * *'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: "0.111.3"
        extended: true

    - uses: actions/setup-node@v3
      with:
        node-version: "18"
        cache: "npm"

    - name: Build
      run: |
        npm i
        hugo --minify

    - name: Publish
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: storage.bunnycdn.com
        username: ${{ secrets.BUNNY_STORAGE }}
        password: ${{ secrets.BUNNY_API_STORAGE }}
        local-dir: ./public/
        server-dir: ./${{ secrets.BUNNY_STORAGE }}/

    - name: Refresh
      run: |
        set -e
        curl --request POST \
            --url https://api.bunny.net/pullzone/${{ secrets.BUNNY_PULL_ZONE }}/purgeCache \
            --header 'AccessKey: ${{ secrets.BUNNY_API }}' \
            --header 'content-type: application/json'
